spring:
  application:
    name: Project REST
    api-prefix: /api/v1.0
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

server:
  port: 24110
